<main>
<section class="section-presenting">
	<div class="container">
    <div class="row">
      <div class="col-sm-6"> <img src="images/comunicare.jpg" class="img-responsive" alt=""> </div>
			<div class="col-sm-6">
				<h1>Mauris elit leo, fringilla vitae </h1>
				<p>Miezul unei societati deschise este unul dinamic. Influentam si suntem influentati, iar comunicarea reprezinta liantul, cel prin care ne formam si ne schimbam/ modificam perceptiile, atitudinile si chiar comporamentele. Comunicarea institutionala detaseaza institutia de serviciile oferite. Afirmarea propriilor valori reprezinta un obiectiv in sine, insa comunicarea impactului misiunii sale culturale/ economice/ sociale etc in comunitatea din care face parte reprezinta o tinta cu o miza mult mai mare. Comunicarea institutionala este adesea pusa in relatie cu reputatia si imaginea publica a institutiilor, pentru ca favorabilitatea acestora determina existenta unui anumit climat de opinie la nivel comunitar, care poate influenta felul in care mesajele vehiculate ajung la publicul tinta sau la membrii comunitatii locale in ansamblul ei. </p>
        <p>Agrafics Communication are in spate o experienta notabila de mai bine de … proiecte in domeniul comunicarii institutionale si vine in sprijinul clientilor sai institutionali cu seturi de solutii complete si o gama de servicii diversificata pentru a face fata si celor mai exigente cerinte. Comunicarea institutionala este profund ancorata in realitate, se redefineste si se remodeleaza constant, ca suma a interactiunilor umane la acelasi nivel sau la niveluri diferite, ce da masura actiunilor viitoare.</p>
			</div>
		</div>
	</div>
</section>
<section class="grey">
	<div class="container">
    <div class="row top-spaced">
			<div class="col-sm-6">
        <h2 id="publicitate">publicitate</h2>
        <p>Publicitatea este una dintre cele mai complexe ramuri ale comunicarii, deoarece actioneaza atat la nivel rational, dar mai ales la nivel emotional. De cele mai multe ori, o traire, o emotie pe care un brand o transmite consumatorului poate crea o legatura intre brand si consumator ce trece dincolo de relatia produs-consumator. Se ajunge astfel la o situatie ideala, de identificare a consumatorului cu brand-ul. Specialistii agentiei in materie de publicitate si mass-media cunosc pasii ce trebuie parcursi, pentru ca brand-ul clientilor nostri sa isi atinga obiectivul. Este nevoie de o cunoastere exhaustiva a targetului, de o strategie de brand corelata cu strategia de comunicare, de mesaje adecvate, livrate intr-un mod adecvat si de o evaluare continua a brand-ului pe toata durata campaniei</p>
        <p>Noi suntem mereu pregatiti in asteptarea unor noi provocari. De mai bine de un deceniu, am asigurat clientilor nostri solutii tehnice de calitate atat in ceea ce priveste proiectarea si elaborarea de strategii complexe in campanii integrate (pentru diversi clienti: companii de stat, dar si ministere, autoritati publice centrale si locale si organizatii non-guvernamentale), cat si in ceea ce priveste prestarea de servicii specific de creatie/ productie publicitara, planificare si cumparare spatii media sau monitorizarea si raportarea.</p>
<p>Am identificat, de-a lungul timpului, nu doar cele mai sofisticate metode de planificare media, ci si pe cele mai eficiente din punct de vedere economic. Bugetele rulate si interactiunea frecventa cu mass-media ne permit astazi sa le oferim clientilor nostri cele mai bune conditii de achizitie de spatii media (presa scrisa, radio, TV, indoor, outdoor, new media), respectand legislatia nationala si europeana in domeniu.</p>
        <h2 id="organizarea-de-evenimente">organizarea de evenimente</h2>
        <p>Evenimentele angajeaza, emotioneaza, pun oamenii in legatura, creaza relatii si, in cele din urma, creaza actiune. Fie ca avem in vedere evenimentele de relatii publice, pe cele clasice de tipul atelierelor de lucru, seminariilor, conferintelor, targurilor sau pe cele mai putin conventionale, organizarea de evenimente ca forma de comunicare directa cu un public sau mai multe, presupune atat exercitarea unui anumit control asupra mesajelor lansate public, cat si crearea unei atmosfere si a unui anumit tip de relatie cu acesta/ acestea.</p>
        <p>Numai in anul 2015, echipa agentiei a implementat cu succes un numar de … evenimente in acelasi timp, atat in Romania, cat si dincolo de granitele tarii. Avem un singur proiect in care … evenimente au fost implementate in … luni. Desi serviciile asigurate de Agrafics Communication au fost extrem de variate, de la elaborare de strategie de comunicare, consultanta si management de proiect pana la furnizare servicii de creatie, catering sau promotionale, evenimentele au solicitat intotdeauna un numar foarte mare de resurse pe multe planuri, atat in timp real, in teren, cat si ca disponibilitate interna de a gasi solutiile optime pentru diverse situatii neprevazute care pot aparea in asemenea conjunctura. De la seminarii si ateliere de lucru la vizite de studii si schimburi de experienta in strainatate le-am facut pe toate, fie in contracte de achizitie publica, fie in proiecte cu finantare nerambursabila directa. Daca am transforma sumele decontate pe transport in kilometri de sosea, am reusi sa facem inconjurul Romaniei de … ori. Da, am reusit sa depasim bariere mai greu de trecut de alte agentii, iar acest lucru ne responsabilizeaza spre a proceda la un nivel cel putin similar si in viitor, castigandu-ne increderea clientilor nostri, pe care vom lupta mereu sa o pastram.</p>
          </div>
      <div class="col-sm-6">
        <h2 id="relatii-publice">relatii publice</h2>
        <p>Construim relatii durabile, bazate pe incredere. Printre premisele asumate in elaborarea programelor de relatii publice se numara responsabilitatea, calitatea, continuitatea si credibilitatea relatiei pe care o construim intre o organizatie si publicul ei. Am construit de-a lungul timpului programe de comunicare strategica eficiente pentru clientii nostri, sustinute de o cercetare si o analiza cuprinzatoare pentru a intelege cum (si de ce) este perceputa o organizatie sau institutie de catre publicul intern si extern. De la auditul comunicarii si pana la relatia cu mass-media, fiecare inel al acestui lant este deosebit de important si tratat cu toata seriozitatea, cunoasterea si expertiza acumulate la nivel de agentie.</p>
<p>Echipa Agrafics Communication este alaturi de clientii sai 24 de ore pe zi, sapte zile pe saptamana. Respectand clauzele de confidentialitate, putem spune doar ca, de-a lungul anilor, Agrafics Communication a manageriat crize care au implicat accidente de mediu, accidente de munca, discriminare la locul de munca, litigii sau acuzatii de coruptie.</p>
<p>Reputatia nu se cumpara si nici nu se obtine in urma unor cheltuieli ocazionale de PR. Ea se castiga in timp, printr-o strategie inspirata si eficienta, prin atentia acordata detaliilor si multa munca. Construirea reputatiei este un proces in care ne implicam pe termen lung, sprijinindu-ne clientii in evitarea riscurilor, la care sunt expusi permanent si in valorificarea oportunitatilor aparute.</p>
<p>In ceea ce priveste relatia cu comunitatea, Agrafics Communication a conceput si a implementat programe de responsabilite sociala care se bazeaza pe analiza atenta a nevoilor comunitatii in care clientii sau partenerii nostri, care ne-au solicitat sprijinul, actioneaza. Rolul agentiei in cadrul acestui tip de proiecte nu este doar acela de a planifica activitatile si de a comunica rezultatele implicarii, ci, in primul rand, acela de a recomanda acele activitati si asocieri care sunt in concordanta cu pozitionarea, valorile si misiunea companiei. Echipa Agrafics Communication a sprijinit benevol cauze si s-a implicat in campanii sociale derulate de diversi actori din mediul ONG an de an pana in prezent si va continua sa o faca, aceasta reprezentand contributia pe care Agrafics Communication o aduce comunitatii.</p>
      <img src="images/comunicare-grup.jpg" class="img-responsive" alt="">
    </div>
		</div>
	</div>
</section>
</main>
