<main>
<section class="section-presenting">
	<div class="container">
    <div class="row">
			<div class="col-sm-6"> <img src="images/consultanta.jpg" class="img-responsive" alt=""> </div>
			<div class="col-sm-6">
				<h1>Etiam egestas a massa sed gravida. Phasellus at erat aliquet, malesuada leo ac.</h1>
				<p>Noi consideram consultanta ca fiind un intreg proces, prezenta in tot ceea ce facem, nu doar o gama de servicii oferita clientilor nostri. Suntem alaturi de clientii nostri de la semnarea contractului si pana la sfarsit in toate etapele, iar istoria a demonstrat ca si dupa… </p>
				<p>Procesul de consultanta presupune interactiune la un nivel complex si atat de dinamic, incat relatiile dintre elementele procesuale se remodeleaza constant, in fiecare etapa, in functie de cercetarile, analizele si studiile realizate, nevoile si conditionarile clientilor nostri si ale proiectelor acestora, precum si in functie de actiunea diversilor factori externi care influenteaza mediul de referinta. </p>
				<p>Informatiile obtinute genereaza anumite recomandari, implementarea acestora si evaluarea solutiilor implementate pentru rezolvarea problemelor semnalate dau masura si impun directia actiunilor urmatoare, astfel incat acest proces se reia sub alta forma de fiecare data, adaptat tuturor situatiilor specifice. </p>
		</div>
		</div>
	</div>
</section>
<section class="grey">
	<div class="container">
    <div class="row top-spaced">
			<div class="col-sm-6">
        <h2 id="cercetare-si-analiza">cercetare si analiza</h2>
        <p>Donec rutrum ac tortor et vulputate. Pellentesque id diam ornare, scelerisque orci vitae, fermentum sapien. Nunc eu nisi id neque dignissim tempus vel hendrerit risus. Ut pharetra sed augue id congue. Praesent et consectetur est. Pellentesque nec est dictum, pretium tortor in, commodo ligula. Donec eget lectus ultrices, malesuada arcu ut, tincidunt arcu.</p>

        <p>Vivamus non porta elit. Curabitur molestie magna est, nec porttitor mauris dignissim quis. Nunc sed metus elementum nibh venenatis ornare. Aliquam leo neque, tristique non viverra nec, gravida a massa. Nam vel mi gravida, placerat dui ut, venenatis purus. Etiam in orci non lorem aliquet volutpat. Suspendisse eget purus vitae tellus dictum iaculis in at tortor. Aliquam eget arcu arcu. Curabitur orci justo, ultrices vitae ex lobortis, sagittis accumsan mauris. Etiam auctor et nisl sed posuere. Donec molestie purus nulla, id consectetur leo vestibulum sed. Nullam varius orci sed orci eleifend, eu accumsan augue varius. Nunc et ligula rhoncus, consectetur diam at, vulputate nunc. Vestibulum sit amet semper erat, et euismod justo. Suspendisse laoreet lectus in lacus accumsan, ac fringilla ligula consectetur.</p>
        <h2 id="parteneriate-internationale">parteneriate internationale</h2>
        <p>Mauris finibus magna et metus dignissim dapibus. Nunc vestibulum scelerisque libero, vel elementum erat commodo non. Sed egestas venenatis ligula sed dictum. Praesent vitae massa ut leo consectetur aliquet. Duis fringilla velit ut condimentum rutrum. Fusce dignissim augue ex, et finibus erat rhoncus et. Donec vitae ante ex. Quisque convallis varius felis. Aenean odio ligula, laoreet eu dolor in, volutpat ornare ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
        <p>Maecenas vitae mauris finibus purus efficitur eleifend eget vitae nisl. Quisque non mauris dignissim, molestie velit et, accumsan felis. Pellentesque mollis turpis id risus mollis, id euismod felis gravida. Sed sed tristique lorem. Ut bibendum molestie augue, at imperdiet quam tempor ut. Morbi arcu justo, hendrerit ac auctor sed, suscipit a dui. Curabitur eu nulla mauris. Curabitur eu lectus consequat, cursus elit in, elementum arcu. Morbi tincidunt hendrerit sagittis. In sed ullamcorper est, a pharetra tortor. Etiam quam nunc, ullamcorper vel pulvinar eget, consectetur a sem.</p>
        <p>Proin in turpis sapien. Cras ligula leo, facilisis quis massa rhoncus, semper rutrum velit. Aenean auctor nulla vel rutrum tempor. Duis congue massa urna, nec fermentum magna aliquet fermentum. Nullam magna dui, elementum ut sollicitudin ac, tristique tristique enim. Pellentesque eget tellus ultrices metus consectetur vestibulum. Maecenas eu sagittis elit. Cras et nibh viverra, malesuada nisi a, ultricies sem. Donec dignissim ligula a elit pretium tempor. Nulla facilisi. Sed feugiat viverra eros, sed euismod elit gravida blandit. Pellentesque luctus arcu vel viverra tristique. In hac habitasse platea dictumst. Morbi ultricies eu tortor id auctor. Nam sit amet nisl in massa lacinia varius et vel metus. Etiam non sem vulputate ex consectetur maximus sed a urna.</p>
        <h2 id="achizitii-publice">achizitii publice</h2>
        <p>Aenean bibendum ornare ullamcorper. Mauris vehicula tristique felis in auctor. Vestibulum tristique felis sed viverra dignissim. Vestibulum imperdiet vestibulum fermentum. Praesent consequat lacus nec semper vehicula. Sed gravida nisl interdum libero porta pretium. In non consequat tellus. In quis vestibulum neque.</p>
        <p>Maecenas eleifend, eros et consectetur convallis, nulla purus malesuada justo, vitae molestie elit massa ut nulla. Nullam sit amet gravida justo, a lacinia sem. Curabitur risus elit, sodales et risus at, rhoncus rhoncus nibh. Praesent pellentesque egestas aliquet. Sed ullamcorper non lacus id tincidunt. Integer aliquet orci lorem, id dictum turpis viverra dignissim. In ac libero arcu. Nulla a libero dolor. Suspendisse efficitur, sem ut feugiat tincidunt, ex ante luctus lectus, sit amet elementum libero nunc sit amet tellus. Fusce efficitur elementum commodo. Sed ac justo tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam erat volutpat.</p>
        <p>Etiam congue faucibus diam, a faucibus nisl vehicula id. Mauris vitae viverra est. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In ut massa quis lorem pellentesque feugiat. Duis in pellentesque arcu. Vestibulum dolor neque, volutpat vitae nunc in, porttitor pretium purus. Fusce bibendum tortor vitae enim hendrerit vestibulum. Quisque consequat nisl vel orci consequat bibendum. Integer sagittis eros neque, id congue arcu rutrum eget. Quisque dapibus interdum ligula, quis ullamcorper elit placerat vel. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla eget laoreet arcu, eget eleifend diam. In viverra purus non tincidunt ultrices. Mauris ut magna congue nibh tincidunt feugiat.</p>
      </div>
      <div class="col-sm-6">
        <h2 id="expertiza-si-asistenta-tehnica">expertiza si asistenta tehnica</h2>
        <p>Curabitur semper nibh eleifend ornare egestas. Phasellus a odio molestie, eleifend tellus a, sagittis enim. Mauris laoreet aliquam orci, sit amet volutpat mauris. Pellentesque sit amet est ligula. Curabitur tempor est rhoncus consequat congue. Vestibulum fermentum et orci a iaculis. Phasellus ut blandit nulla. Suspendisse at tempus magna. Donec hendrerit lectus arcu, ac commodo urna elementum vel. Donec a lectus convallis, gravida leo nec, luctus arcu. Quisque pulvinar enim a libero finibus, eleifend porta leo varius. Aliquam accumsan ante vel hendrerit egestas. Aenean eget tortor dictum, tempor justo sit amet, ultrices massa.</p>

        <p>Integer convallis porttitor massa non gravida. Duis lobortis iaculis hendrerit. Nullam vel faucibus odio. Nam lobortis lacus semper leo porta finibus. Aenean id dignissim sem, eu pretium nunc. Etiam a imperdiet nunc. Quisque sit amet aliquet elit. Pellentesque ac aliquet odio. Suspendisse ornare quam ut dui mollis, id viverra diam finibus. Fusce dictum risus risus, nec efficitur dui iaculis quis. Nullam consequat turpis ut congue ornare. Nunc nec turpis a elit elementum pellentesque sit amet eu justo. Fusce fermentum dui vel erat molestie, vitae hendrerit nunc fringilla. Nunc et mattis sem. Phasellus vitae auctor dui, in fringilla massa.</p>
        <p>Fusce ac metus sed purus rhoncus rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec accumsan ligula. Nunc quis tempus metus. Nam euismod est lacus, nec imperdiet ex sagittis quis. Mauris in viverra mauris. Pellentesque egestas convallis dui, vel cursus erat pulvinar sed. Nam justo risus, varius ultricies scelerisque eleifend, tincidunt ac nunc.</p>
      <img src="images/consultanta-oameni.jpg" class="img-responsive" alt="">
      <h2 id="accesare-fonduri-nerambursabile">accesare fonduri nerambursabile</h2>
      <p>Morbi consectetur, lorem id ullamcorper sollicitudin, arcu metus semper ipsum, vel ultrices nibh libero sit amet tellus. Curabitur eleifend, arcu sed aliquam placerat, neque mi sollicitudin neque, sit amet suscipit lacus nibh non purus. Ut cursus nulla a blandit luctus. Morbi ultrices mollis tempor. Integer erat ipsum, elementum ut sagittis cursus, bibendum at ex. Proin consectetur at tellus quis porta. Phasellus facilisis molestie suscipit.</p>
      <p>Nam malesuada nisl et tortor ultrices facilisis. Donec eu laoreet quam, ac euismod ligula. Curabitur nec diam cursus, sagittis odio id, euismod dui. Sed blandit at eros vitae suscipit. Proin dignissim urna ac diam fringilla scelerisque. Mauris quis interdum dui. Nunc eget nibh dignissim, dapibus mi id, bibendum leo.</p>
      <p>Pellentesque urna ipsum, aliquam ac facilisis at, imperdiet non elit. Praesent ultricies ac leo non porttitor. Cras at orci sit amet ex vestibulum molestie. Mauris a tincidunt libero. Nam vulputate purus quam, vitae mollis magna congue sit amet. Donec auctor interdum leo in scelerisque. Suspendisse ultricies sit amet lorem ut tincidunt. Suspendisse congue at nisl id blandit. Donec orci quam, finibus vitae lacus in, hendrerit imperdiet enim. Donec eu diam ligula. Quisque mattis dolor eget lorem hendrerit, sit amet venenatis odio faucibus. Morbi mollis facilisis accumsan. Aenean non elit odio. Nulla elementum congue odio vel convallis. Ut faucibus purus et ligula convallis efficitur quis ac odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
      </div>
		</div>
	</div>
</section>
</main>
