<main>
<section class="section-presenting">
	<div class="container">
    <div class="row">
			<div class="col-sm-6"> <img src="images/consultanta.jpg" class="img-responsive" alt=""> </div>
			<div class="col-sm-6">
				<h1>Etiam egestas a massa sed gravida. Phasellus at erat aliquet, malesuada leo ac.</h1>
				<p>Noi consideram consultanta ca fiind un intreg proces, prezenta in tot ceea ce facem, nu doar o gama de servicii oferita clientilor nostri. Suntem alaturi de clientii nostri de la semnarea contractului si pana la sfarsit in toate etapele, iar istoria a demonstrat ca si dupa… </p>
				<p>Procesul de consultanta presupune interactiune la un nivel complex si atat de dinamic, incat relatiile dintre elementele procesuale se remodeleaza constant, in fiecare etapa, in functie de cercetarile, analizele si studiile realizate, nevoile si conditionarile clientilor nostri si ale proiectelor acestora, precum si in functie de actiunea diversilor factori externi care influenteaza mediul de referinta. </p>
				<p>Informatiile obtinute genereaza anumite recomandari, implementarea acestora si evaluarea solutiilor implementate pentru rezolvarea problemelor semnalate dau masura si impun directia actiunilor urmatoare, astfel incat acest proces se reia sub alta forma de fiecare data, adaptat tuturor situatiilor specifice. </p>
		</div>
		</div>
	</div>
</section>
<section class="grey">
	<div class="container">
    <div class="row top-spaced">
			<div class="col-sm-6">
        <h2 id="cercetare-si-analiza">cercetare si analiza</h2>
        <p>Agrafics Communication furnizeaza intreaga gama de servicii specifice pentru elaborarea de programe generatoare de idei, inclusiv focus-grupuri, interviuri, analize, studii de opinie, evaluari si investigatii speciale. Aceasta cercetare devine fundamentul recomandarilor urmatoare, avand aceeasi importanta in garantarea eficientei si a valorii lor in timp. Serviciile furnizate de agentia noastra au sprijinit dezvoltarea unor proiecte ambitioase din cele mai diverse domenii, de la managementul deseurilor la politici publice, dar si campanii de comunicare interna pentru companii romanesti de traditie din domeniul energetic sau analiza nevoilor unor comunitati defavorizate. Provocarile ridicate de clientii nostri nu ne-au speriat niciodata, ne-au responsabilizat mai degraba, pentru ca fiecare proiect nou poarta cu sine si amprenta istoriei rezultatelor proiectelor trecute pe care avem datoria morala de a o onora si in continuare</p>
        <h2 id="parteneriate-internationale">parteneriate internationale</h2>
        <p>Atunci cand arta se intalneste cu stiinta sau atunci cand talentul se intalneste cu iscusinta…</p>
        <p>Portofoliul nostru de proiecte internationale ne-a adus in contact atat cu experti reputati pe piata internationala de profil, cat si cu parteneri valorosi carora le putem solicita implicarea in viitoarele consortii, alaturi de agentia noastra. Atunci cand ne gandim la partea de finantare a proiectelor, un investitor va cauta intotdeauna o structura de parteneri consolidata si validata atat prin experienta acumulata la nivelul membrilor consortiului, cat si prin capitalizarea experientei adunate la nivelul executivilor din firmele respective. Agrafics Communication a adunat in jurul sau, de-a lungul timpului, parteneri de renume din majoritatea tarilor europene (Franta, Germania, Italia, Spania, Portugalia, Irlanda, Letonia, Austria, Danemarca, Belgia etc) in care am derulat proiecte de schimb de experienta si know-how, dar si din China, Canada sau USA. Partenerii nostri din aceste tari fac parte din categoria firmelor/ agentiilor de consultanta, agentii de comunicare/ publicitate, institutii de invatamant, institute de cercetare, agentii de organizare evenimente internationale, organizatori de targuri si expozitii din afara Romaniei, autoritati publice centrale si locale, beneficiari ai fondurilor europene etc.</p>
        <h2 id="achizitii-publice">achizitii publice</h2>
        <p>Agrafics Communication are un departament specializat pe Achizitii publice cu o echipa formata din consilieri juridici si specialisti achizitii publice. Aceasta echipa coordoneaza o parte foarte importanta a activitatii noastre, gestionand intregul proces care sta in spatele oricarui tip de procedura de achizitii publice de la elaborarea documentatiei de atribuire si pana la atribuirea contractelor cu intocmirea tuturor documentelor specifice si indeplinirea tuturor formalitatilor birocratice necesare in cadrul oricarui proiect.</p>
<p>Acest departament asigura si continuitatea si sustenabilitatea marelui proiect Agrafics Communication prin intocmirea documentatiei de calificare, dar si a ofertei tehnico-financiara pentru participarea companiei la procedurile de achizitie publica specifice domeniului nostru de activitate, avand ca rezultat intrarea in implementare a proiectelor unor mai vechi sau mai noi clienti institutionali.</p>
<p>Suntem obisnuiti asadar sa fim de ambele parti ale baricadei, atat in calitate de ofertanti cat si in calitate de autoritate contractanta. Din aceasta perspectiva si din cea a experientei acumulate in cei mai bine de 10 ani de cand echipa noastra lucreaza in domeniul achizitiilor publice, suntem cei mai potriviti consultanti pentru acest domeniu sensibil, fie ca sunteti autoritate contractanta sau potential ofertant.</p>
        <p>Maecenas eleifend, eros et consectetur convallis, nulla purus malesuada justo, vitae molestie elit massa ut nulla. Nullam sit amet gravida justo, a lacinia sem. Curabitur risus elit, sodales et risus at, rhoncus rhoncus nibh. Praesent pellentesque egestas aliquet. Sed ullamcorper non lacus id tincidunt. Integer aliquet orci lorem, id dictum turpis viverra dignissim. In ac libero arcu. Nulla a libero dolor. Suspendisse efficitur, sem ut feugiat tincidunt, ex ante luctus lectus, sit amet elementum libero nunc sit amet tellus. Fusce efficitur elementum commodo. Sed ac justo tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam erat volutpat.</p>
        <p>Etiam congue faucibus diam, a faucibus nisl vehicula id. Mauris vitae viverra est. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In ut massa quis lorem pellentesque feugiat. Duis in pellentesque arcu. Vestibulum dolor neque, volutpat vitae nunc in, porttitor pretium purus. Fusce bibendum tortor vitae enim hendrerit vestibulum. Quisque consequat nisl vel orci consequat bibendum. Integer sagittis eros neque, id congue arcu rutrum eget. Quisque dapibus interdum ligula, quis ullamcorper elit placerat vel. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla eget laoreet arcu, eget eleifend diam. In viverra purus non tincidunt ultrices. Mauris ut magna congue nibh tincidunt feugiat.</p>
      </div>
      <div class="col-sm-6">
        <h2 id="expertiza-si-asistenta-tehnica">expertiza si asistenta tehnica</h2>
        <p>Curabitur semper nibh eleifend ornare egestas. Phasellus a odio molestie, eleifend tellus a, sagittis enim. Mauris laoreet aliquam orci, sit amet volutpat mauris. Pellentesque sit amet est ligula. Curabitur tempor est rhoncus consequat congue. Vestibulum fermentum et orci a iaculis. Phasellus ut blandit nulla. Suspendisse at tempus magna. Donec hendrerit lectus arcu, ac commodo urna elementum vel. Donec a lectus convallis, gravida leo nec, luctus arcu. Quisque pulvinar enim a libero finibus, eleifend porta leo varius. Aliquam accumsan ante vel hendrerit egestas. Aenean eget tortor dictum, tempor justo sit amet, ultrices massa.</p>

        <p>Integer convallis porttitor massa non gravida. Duis lobortis iaculis hendrerit. Nullam vel faucibus odio. Nam lobortis lacus semper leo porta finibus. Aenean id dignissim sem, eu pretium nunc. Etiam a imperdiet nunc. Quisque sit amet aliquet elit. Pellentesque ac aliquet odio. Suspendisse ornare quam ut dui mollis, id viverra diam finibus. Fusce dictum risus risus, nec efficitur dui iaculis quis. Nullam consequat turpis ut congue ornare. Nunc nec turpis a elit elementum pellentesque sit amet eu justo. Fusce fermentum dui vel erat molestie, vitae hendrerit nunc fringilla. Nunc et mattis sem. Phasellus vitae auctor dui, in fringilla massa.</p>
        <p>Fusce ac metus sed purus rhoncus rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec accumsan ligula. Nunc quis tempus metus. Nam euismod est lacus, nec imperdiet ex sagittis quis. Mauris in viverra mauris. Pellentesque egestas convallis dui, vel cursus erat pulvinar sed. Nam justo risus, varius ultricies scelerisque eleifend, tincidunt ac nunc.</p>
      <img src="images/consultanta-oameni.jpg" class="img-responsive" alt="">
      <h2 id="accesare-fonduri-nerambursabile">accesare fonduri nerambursabile</h2>
      <p>Morbi consectetur, lorem id ullamcorper sollicitudin, arcu metus semper ipsum, vel ultrices nibh libero sit amet tellus. Curabitur eleifend, arcu sed aliquam placerat, neque mi sollicitudin neque, sit amet suscipit lacus nibh non purus. Ut cursus nulla a blandit luctus. Morbi ultrices mollis tempor. Integer erat ipsum, elementum ut sagittis cursus, bibendum at ex. Proin consectetur at tellus quis porta. Phasellus facilisis molestie suscipit.</p>
      <p>Nam malesuada nisl et tortor ultrices facilisis. Donec eu laoreet quam, ac euismod ligula. Curabitur nec diam cursus, sagittis odio id, euismod dui. Sed blandit at eros vitae suscipit. Proin dignissim urna ac diam fringilla scelerisque. Mauris quis interdum dui. Nunc eget nibh dignissim, dapibus mi id, bibendum leo.</p>
      <p>Pellentesque urna ipsum, aliquam ac facilisis at, imperdiet non elit. Praesent ultricies ac leo non porttitor. Cras at orci sit amet ex vestibulum molestie. Mauris a tincidunt libero. Nam vulputate purus quam, vitae mollis magna congue sit amet. Donec auctor interdum leo in scelerisque. Suspendisse ultricies sit amet lorem ut tincidunt. Suspendisse congue at nisl id blandit. Donec orci quam, finibus vitae lacus in, hendrerit imperdiet enim. Donec eu diam ligula. Quisque mattis dolor eget lorem hendrerit, sit amet venenatis odio faucibus. Morbi mollis facilisis accumsan. Aenean non elit odio. Nulla elementum congue odio vel convallis. Ut faucibus purus et ligula convallis efficitur quis ac odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
      </div>
		</div>
	</div>
</section>
</main>
