<main>
<section class="section-presenting">
	<div class="container">
    <div class="row">
			<div class="col-sm-6"> <img src="/images/consultanta.jpg" class="img-responsive" alt=""> </div>
			<div class="col-sm-6">
				<h1>Mai mult decat un pachet de servicii</h1>
				<p>Noi consideram consultanta ca fiind un intreg proces, prezenta in tot ceea ce facem, nu doar o gama de servicii oferita clientilor nostri. Suntem alaturi de clientii nostri de la semnarea contractului si pana la sfarsit in toate etapele, iar istoria a demonstrat ca si dupa… </p>
				<p>Procesul de consultanta presupune interactiune la un nivel complex si atat de dinamic, incat relatiile dintre elementele procesuale se remodeleaza constant, in fiecare etapa, in functie de cercetarile, analizele si studiile realizate, nevoile si conditionarile clientilor nostri si ale proiectelor acestora, precum si in functie de actiunea diversilor factori externi care influenteaza mediul de referinta. </p>
				<p>Informatiile obtinute genereaza anumite recomandari, implementarea acestora si evaluarea solutiilor implementate pentru rezolvarea problemelor semnalate dau masura si impun directia actiunilor urmatoare, astfel incat acest proces se reia sub alta forma de fiecare data, adaptat tuturor situatiilor specifice. </p>
		</div>
		</div>
	</div>
</section>
<section class="grey">
	<div class="container">
    <div class="row top-spaced">
			<div class="col-sm-6">
        <h2 id="cercetare-si-analiza">cercetare si analiza</h2>
        <p>Agrafics Communication furnizeaza intreaga gama de servicii specifice pentru elaborarea de programe generatoare de idei, inclusiv focus-grupuri, interviuri, analize, studii de opinie, evaluari si investigatii speciale. Aceasta cercetare devine fundamentul recomandarilor urmatoare, avand aceeasi importanta in garantarea eficientei si a valorii lor in timp. Serviciile furnizate de agentia noastra au sprijinit dezvoltarea unor proiecte ambitioase din cele mai diverse domenii, de la managementul deseurilor la politici publice, dar si campanii de comunicare interna pentru companii romanesti de traditie din domeniul energetic sau analiza nevoilor unor comunitati defavorizate. Provocarile ridicate de clientii nostri nu ne-au speriat niciodata, ne-au responsabilizat mai degraba, pentru ca fiecare proiect nou poarta cu sine si amprenta istoriei rezultatelor proiectelor trecute pe care avem datoria morala de a o onora si in continuare</p>
        <h2 id="parteneriate-internationale">parteneriate internationale</h2>
        <p>Atunci cand arta se intalneste cu stiinta sau atunci cand talentul se intalneste cu iscusinta…</p>
        <p>Portofoliul nostru de proiecte internationale ne-a adus in contact atat cu experti reputati pe piata internationala de profil, cat si cu parteneri valorosi carora le putem solicita implicarea in viitoarele consortii, alaturi de agentia noastra. Atunci cand ne gandim la partea de finantare a proiectelor, un investitor va cauta intotdeauna o structura de parteneri consolidata si validata atat prin experienta acumulata la nivelul membrilor consortiului, cat si prin capitalizarea experientei adunate la nivelul executivilor din firmele respective. Agrafics Communication a adunat in jurul sau, de-a lungul timpului, parteneri de renume din majoritatea tarilor europene (Franta, Germania, Italia, Spania, Portugalia, Irlanda, Letonia, Austria, Danemarca, Belgia etc) in care am derulat proiecte de schimb de experienta si know-how, dar si din China, Canada sau USA. Partenerii nostri din aceste tari fac parte din categoria firmelor/ agentiilor de consultanta, agentii de comunicare/ publicitate, institutii de invatamant, institute de cercetare, agentii de organizare evenimente internationale, organizatori de targuri si expozitii din afara Romaniei, autoritati publice centrale si locale, beneficiari ai fondurilor europene etc.</p>
        <h2 id="achizitii-publice">achizitii publice</h2>
        <p>Agrafics Communication are un departament specializat pe Achizitii publice cu o echipa formata din consilieri juridici si specialisti achizitii publice. Aceasta echipa coordoneaza o parte foarte importanta a activitatii noastre, gestionand intregul proces care sta in spatele oricarui tip de procedura de achizitii publice de la elaborarea documentatiei de atribuire si pana la atribuirea contractelor cu intocmirea tuturor documentelor specifice si indeplinirea tuturor formalitatilor birocratice necesare in cadrul oricarui proiect.</p>
<p>Acest departament asigura si continuitatea si sustenabilitatea marelui proiect Agrafics Communication prin intocmirea documentatiei de calificare, dar si a ofertei tehnico-financiara pentru participarea companiei la procedurile de achizitie publica specifice domeniului nostru de activitate, avand ca rezultat intrarea in implementare a proiectelor unor mai vechi sau mai noi clienti institutionali.</p>
<p>Suntem obisnuiti asadar sa fim de ambele parti ale baricadei, atat in calitate de ofertanti cat si in calitate de autoritate contractanta. Din aceasta perspectiva si din cea a experientei acumulate in cei mai bine de 10 ani de cand echipa noastra lucreaza in domeniul achizitiilor publice, suntem cei mai potriviti consultanti pentru acest domeniu sensibil, fie ca sunteti autoritate contractanta sau potential ofertant.</p>
      </div>
      <div class="col-sm-6">
        <h2 id="expertiza-si-asistenta-tehnica">expertiza si asistenta tehnica</h2>
        <p>Echipa agentiei noastre are un nucleu dur de experti in jurul caruia s-au adunat de-a lungul timpului multi colaboratori mai mult sau mai putin reputati, dar cu recomandari serioase in portofoliu. Sute de astfel de experti s-au alaturat echipei noastre extinse si impreuna am implementat proiecte ambitioase si din cele mai diverse, ca rezultate propuse, grup tinta sau complexitate. Fie ca ne gandim la studii si analize, politici publice, formare profesionala, achizitii publice, comunicare, asistenta tehnica sau domenii mult mai specifice, baza noastra de date se imbogateste constant cu resurse umane din Romania sau din afara Romaniei, care pot aduce plusvaloare proiectelor actualilor si viitorilor nostri parteneri de proiect prin pregatirea, seriozitatea si profesionalismul pe care acestia sunt obisnuiti sa le aduca in orice relatie de colaborare</p>
<p>Serviciile de asistenta tehnica asigurate de agentia noastra pentru clientii institutionali cu care am colaborat pana in prezent ne-au permis o cunoastere mai profunda a publicului tinta al acestora, dar si a activitatii organizationale in sine, prin complexitatea cerintelor, precum si multitudinea de oportunitati ivite pentru a identifica solutii creative de depasire a unor situatii adeseori “delicate”. Astfel, de-a lungul timpului, Agrafics Communication a oferit consultanta si asistenta tehnica in implementare pe proiecte finantate din fonduri europene pentru un numar mare de institutii publice, dovedindu-se un partener de anvergura pentru clientii sai. Expertiza noastra in proiectele finantate din fonduri europene cuprinde proiecte POSDRU, PODCA, PNDR, POSMEDIU, POS TRANSPORT, POSCCE, REGIO, programe de cooperare transfrontaliera. Activitatile pe care specialistii agentiei le-au intreprins in cadrul acestor proiecte variaza de la asistenta tehnica pe procese de informare sau publicitate pana la auditul proiectelor sau elaborarea de strategii nationale si politici publice.</p>
      <img src="/images/consultanta-oameni.jpg" class="img-responsive" alt="">
      <h2 id="accesare-fonduri-nerambursabile">accesare fonduri nerambursabile</h2>
      <p>Expertiza Agrafics Communication in managementul proiectelor a fost dobandita prin numeroasele proiecte dezvoltate si implementate pentru clientii nostri. In momentul de fata, fie ca vorbim despre proiecte locale sau proiecte europene cu implicatii nationale sau regionale, suntem pregatiti sa raspundem provocarilor ce decurg dintr-o astfel de activitate.</p>
      <p>Agrafics Communication s-a familiarizat de-a lungul timpului cu toate fazele managementului proiectelor, reusind de fiecare data sa armonizeze toate activitatile, metodele si elementele componente care, in timp, transforma un proiect aflat in faza incipienta intr-unul de succes. Facem parte din categoria beneficiarilor de fonduri nerambursabile, astfel incat nici aceasta experienta nu ne este straina. Ceea ce a urmat a venit pe cale naturala, iar astazi ne bucuram de existenta celei mai tinere divizii din cadrul agentiei, respectiv cea dedicata scrierii de proiecte, din cadrul Departamentului Finantare externa.</p>
<p>Accesam, implementam, monitorizam si implementam proiecte cu finantare nerambursabila, fie din postura de beneficiar, fie din cea de consultant pentru alti beneficiari eligibili.</p>
      </div>
		</div>
	</div>
</section>
</main>
